### ISSUE TITLE
help: I cannot work with opennetmon

### ISSUE THREAD

**Issue by DevelopmentIsKey** [TUDelftNAS/SDN-OpenNetMon#4]
Hi there,
I have been working on a project and I need the opennetmon to monitor my network. I do not know how to use it since I am new to this field. Could anybody help me come up with some ideas about getting to know the opennetmon. I cannot find any tutorial or documentation about it. I will be thankful if you could help me.
Thanks.
Best,

**Comment by NvanAdrichem** [comment]
Dear Fatemeh,

Also in response to your identical e-mail.
Are you familiar with OpenFlow, Open vSwitch and/or POX in general? If not, I suggest you read into those subjects.

OpenNetMon basically is a POX controller module, hence you need a running OpenFlow network (f.e. using physical switches capable of OpenFlow or Open vSwitch switches) and the POX controller to install OpenNetMon upon. I suggest you start out here http://www.noxrepo.org/pox/about-pox/ and here http://sdnhub.org/tutorials/pox/ to learn about POX. POX is also shipped with the Mininet Tutorial, though some students of mine have experienced some problems with Mininet and OpenNetMon, so I suggest you revert to a physical network for your experiments.

Best regards,
Niels

**Comment by NvanAdrichem** [comment]
Handled by e-mail.

**Comment by SadhuRamBasnet** [comment]
Hi there,
Could you guide how to use opennetmon to monitor ? Explain with examples.

Regards
Sadhu Ram Basnet
Country :Nepal

**Comment by DevelopmentIsKey** [comment]
Hi,I used opennetmon just for few month. When you run the controller with startup.py it records information regarding to the throughput and delay in some .csv files which you can find them in one of the folders that I don't remember now, sorry. The files sometimes might be empty. In that case, you should re-run the controller. then with those files you can do whatever you need for your case. or you can change the monitoring.py for your scenario if you want something specific.
Best, 

```
On Thursday, December 24, 2015 4:25 AM, SadhuRamBasnet <notifications@github.com> wrote:
```

 Hi there,
Could you guide how to use opennetmon to monitor ? Explain with examples.Regards
Sadhu Ram Basnet
Country :Nepal—
