### ISSUE TITLE
Unknown host 

### ISSUE THREAD

**Issue by Ali00** [TUDelftNAS/SDN-OpenNetMon#6]
Hello there, 

I have tried to use Opennetmon in a mininet topology that has been designed in [MiniEdit] GUI, but unfortunately I've got the following error message;

Ping: unknown host h1

when I tried to ping h1 with other hosts and the same thing when I tried to ping any other host .
So, could you please advise me in how to resolve this issue.

Many thanks,

Ali

**Comment by NvanAdrichem** [comment]
Hello Ali00,

First of all, can I assume there actually is a host named h1?
Can you try to ping using the corresponding IP-address of the host instead?

Furthermore, there have been issues using OpenNetMon in Mininet, I advise to use a physical setup of a few old machines instead.

I hope this helps.

Best,
Niels

**Comment by Ali00** [comment]
Hello Niels,

Thank you for the clarification, the issue has been solved.

Many thanks,
Ali

**Comment by Ali00** [comment]
One more question :-)

Is it necessary to include the "openflow.discovery" module when run opennetmon ? 
like:
 ./pox.py openflow.discovery opennetmon.monitoring opennetmon.forwarding 

Thanks,

**Comment by NvanAdrichem** [comment]
Hi @Ali00,

Yes, you need the discovery module. If I remember correctly you can use the startup module to launch the right modules and preset the right variables.

Best,
Niels
