### ISSUE TITLE
How to measure the parameters

### ISSUE THREAD

**Issue by MohammedMoin** [TUDelftNAS/SDN-OpenNetMon#7]
Dear sir,
i have installed opennetmon. i am working with pox contoller using mininet.  i want to know how to use opennetmon to monitor the sdn network

**Comment by NvanAdrichem** [comment]
Dear Mohammed,

Have you followed the readme in the root directory and just tried to start a flow between 2 hosts (for example using ping or iperf)? If so, can you tell me where you got stuck, what types of messages you saw and what did and did not work?

Best regards,
Niels
