### ISSUE TITLE
Module not found: openNetMon.startup

### ISSUE THREAD

**Issue by kevhjelm** [TUDelftNAS/SDN-OpenNetMon#8]
So I've been working on SDN and im new to the field, when following the step in the github repo I face a problem where i cant find the opennetmon.startup file. I get an error saying the the module is not found. I have tried to use the startup.py file without any success and tried to look for updated version of the git repo. Have any of you any tips about this or have faced the same problem?

**Comment by reza92farahani** [comment]
Could you solve this problem?
